apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-deployment
  namespace: exchange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
        - name: exchange
          image: dellabeneta/exchange:dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"
