apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-deployment
  namespace: ex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ex
  template:
    metadata:
      labels:
        app: ex
    spec:
      containers:
        - name: ex
          image: dellabeneta/ex:dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"
